# name="michu"
# age=19
# city="vengara"
# print(name)
# print(id(name))
# print(age)
# print(id(age))
# print(city)
# print(id(city))
# a=10
# b=10
# print(a)
# print(b)
# print(id(a))
# print(id(b))
# print(age,city,sep="@")
# a=b=c=10
# print(a)
# print(b)
# print(c)
# print(a,b,c)
# a,b,c=999,24.789,"python interpreter"
# print(a,b,c)
# print(a)
# print(b)
# print(c)